#!/bin/bash

echo -e "\n+++ INSTALLING DEPENDENCIES +++"
sleep 1
sudo curl https://raw.githubusercontent.com/gaetan1903/akory/main/akory > /usr/local/bin/akory
sudo chmod a+rx /usr/local/bin/akory
echo -e "\n+++ TRANSFER-CLI INSTALLATION +++"
sleep 1
sudo curl https://raw.githubusercontent.com/RajaRakoto/transfer-cli/master/transfer-cli > transfer-cli
sudo chmod a+rx transfer-cli
sudo mv transfer-cli /usr/local/bin/
echo -e "\n+++ VERSION CHECKING +++"
sleep 1
transfer-cli --version
echo "You just need to relaunch this installation script 'setup' to update this cli... ENJOY :)"

